### ISSUE TITLE
Change Road Type Labels

### ISSUE THREAD

**Issue by JDWoodcock** [syounkin/ITHIM#12]
split into 2 variables roadtype & severity
Road type: suggested names
Motor only: e.g. freeway, motorway
Major: e.g. Arterial, A road
Minor: e.g. all other including residential streets, B or C roads

**Comment by syounkin** [comment]
@arcean How is this handled in the new road injury code?

**Comment by TSzDefr** [comment]
I think that with the array approach we can introduce this using one column (all possible combinations roadtype-severity) or two columns. Of course all input files (in which these variables are needed) should be changed consequently.
