### ISSUE TITLE
travel time and distance by road type

### ISSUE THREAD

**Issue by JDWoodcock** [syounkin/ITHIM#15]
implement new approach linking travel time to distance

**Comment by syounkin** [comment]
I think the best approach here is to use the trip simulation method used for ICT.  We can estimate the proportional change in person and vehicle distance, by road type, through this simulation, along with travel time, thus linking the two.  ICT can serve as a scenario generator that provides ITHIM with mean travel times, person and vehicle miles, by road type and more.

Survey Data -> ICT Trip Class -> ITHIM Class -> Health Outcomes

The ICT class summarizes the baseline and scenario models into parameters that the ITHIM package can use to create two ITHIM objects (baseline and scenario), and perform the physical activity comparative risk analysis and road injury estimation.

**Comment by JDWoodcock** [comment]
the ICT is a nice way to generate scenarios but it doesnt solve the road type problem itself (as trip level data wont have road type in it). So we still need some kind intermediary step of estimating % of distance by mode by road type. And for cars I think this is best done by assuming a difference between short and longer distnance car trips. If using aggregated data I would just split short vs long, while using individual level data a more complicated rule could be used (if we have data to support it).
I think there are two reasons not to use individual trip simulation approaches
1) if people dont have a travel survey to work with
2) trip switching scenarios are neat but dont allow you to generate all the scenarios that people will be interested in (well not easily anyway)

**Comment by syounkin** [comment]
See issue #23 for continuation.
