### ISSUE TITLE
getGBD gives extraneous warnings

### ISSUE THREAD

**Issue by syounkin** [syounkin/ITHIM#16]
Fix the getGBD method to control the input and output formats better, document them, and suppress warnings caused by the melt function.

**Comment by vargovargo** [comment]
awesome, I'll be testing this with CSV as well as the getBurden functions on the plane today.

**Comment by syounkin** [comment]
This is the method that needs to be addressed.  It simply isn't substantial enough, and is the source of the extraneous warnings.

```r
setMethod("getGBD", signature(x = "ITHIM", format = "character"), function(x, format){
    if(format == "list"){
        return(x@parameters@GBD)
    }else if(format == "data.frame"){
        return(melt(x@parameters@GBD))
    }else{
        message("Error with getGBD format argument.")
        }
})
```
