### ISSUE TITLE
Input File Formats

### ISSUE THREAD

**Issue by syounkin** [syounkin/ITHIM#22]
Normalize all `csv` input files, e.g.,

Instead of:
```r
        Arterial      Highway      Local
walk  0.20641691 5.507203e-08 0.61925072
cycle 0.23757332 3.371519e-08 0.26790183
[...]
```
we have:
```r
mode, roadType, val
walk, Arterial, 0.20641691
walk, Highway, 5.507203e-08
walk, Local, 0.61925072
cycle, Arterial, 0.23757332
[...]
```
Also take care to keep the number of `csv` files needed at a minimum.  Files with default values can be stored in `./inst/`.  These default values should be well-defined somewhere in the documentation.

**Comment by syounkin** [comment]
I'll work on the function `readActiveTransportTime`.

**Comment by syounkin** [comment]
Finished for active transport time and road injuries files.  The files must be ordered properly.  The functions aren't written to handle data in any order.  Some assumptions are made.

**Comment by syounkin** [comment]
Still need to change the file format for disease burden (GBD).  The list of diseases should be fixed and CVD should be given explicitly.

**Comment by vargovargo** [comment]
Does this mean we want require the GBD.csv to eliminate IHD, InflammatoryHD, and HHD out?  reformatGBD handles that currently, yes?
