### ISSUE TITLE
naming 'sum' functions

### ISSUE THREAD

**Issue by vargovargo** [syounkin/ITHIM#3]
the 'sum...' functions , such as sumBreastCancer() returns the change in burden, perhaps we should call it deltaBreastCancer

**Comment by vargovargo** [comment]
create deltaBurden to mirror getBurden but for 2 ITHIM objects

**Comment by vargovargo** [comment]
existing functions for sumDALY and sumBreastCancer, etc can be made aliases to deltaBurden

**Comment by vargovargo** [comment]
`sumDALY(example, scenario)`
     WILL BECOME
`deltaBurden(example, scenario)`

`sumDiabetes(example, scenario)`
     WILL BECOME    
`deltaBurden(example, scenario, bur="daly", dis="Diabetes")`

**Comment by syounkin** [comment]
Done.  Test it out, see if there are any problems.
