### ISSUE TITLE
Check that population distribution, F, is working

### ISSUE THREAD

**Issue by syounkin** [syounkin/ITHIM#6]
Because the cycle times are zero in the referent class in around a dozen states it makes more sense to work with the overall mean.  To do so we need F.

**Comment by vargovargo** [comment]
I have started a script that uses the American Community Survey (the census) API to grab age/gender distribution for any geography we query. I need to put some time into it but I think it would be good to use and could match up well with the geographies we receive from Scott that we'll have to query.

**Comment by vargovargo** [comment]
this example gives total population for every county

`library(jsonlite)`
`#ACS API`
`ACSpop <- as.data.frame(fromJSON("http://api.census.gov/data/2015/acs5?get=B01001_001E,NAME&for=county:*&key=f78d6b6c18608edc379b5a06c55407ceb45e7038"))`
`ACSpop <- ACSpop[-1,]`
`colnames(ACSpop) <- c("ACSpopulation","COUNTY_STATE","stateOnly","countyOnly")`
`ACSpop$countyFIPS <- as.integer(paste(ACSpop$stateOnly, ACSpop$countyOnly, sep=""))`
`rownames(ACSpop) <- ACSpop$countyFIPS`

**Comment by syounkin** [comment]
Can we use this script to find the population stratified by age-sex?

**Comment by vargovargo** [comment]
use this function, enter the state and county fips
https://cobenefitsithim.slack.com/files/vargo/F45GABDM2/acs_tract_age_and_sex.r
